apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.14.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: postgres
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              key: postgresdb
              name: postgresdb
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: postgrespassword
              name: postgrespassword
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: postgresuser
              name: postgresuser
        - name: PGDATA
          valueFrom:
            configMapKeyRef:
              key: PGDATA
              name: postgres-environment-postgres-env
        image: postgres:11
        name: postgres
        ports:
        - containerPort: 5432
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgresvol
      restartPolicy: Always
      volumes:
      - name: postgresvol
        persistentVolumeClaim:
          claimName: postgresvol
status: {}
