apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.14.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: tracker
  name: tracker
spec:
  selector:
    matchLabels:
      io.kompose.service: tracker
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: tracker
    spec:
      containers:
      - env:
        - name: KEYWORDS
          valueFrom:
            configMapKeyRef:
              key: KEYWORDS
              name: tracker-environment-tracker-env
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              key: rabbitpassword
              name: rabbitpassword
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              key: rabbituser
              name: rabbituser
        - name: SOURCES
          valueFrom:
            configMapKeyRef:
              key: SOURCES
              name: tracker-environment-tracker-env
        image: hellgrenj/projects:mediaspin-trackerv30
        name: tracker
        resources: 
          limits: {}
        volumeMounts:
        - mountPath: /logs
          name: logs
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      volumes:
      - name: logs
        persistentVolumeClaim:
          claimName: trackerlogs
status: {}
